config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :stories
    resources :reviews
  end
  resources :stories do
    resources :episodes
  end
  root 'books#index'
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :story

  has_attached_file :episode_img, :styles => { :episode_index => "250x350>", :episode_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :episode_img, :content_type => /\Aimage\/.*\z/
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :set_story, only: [:index, :show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
    @eppisode = Episode.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)
    @episode.story_id = params[:story_id]

    respond_to do |format|
      if @episode.save!
        format.html { redirect_to story_episodes_path, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to story_episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end
    def set_story
      @story = Story.find(params[:story_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:title, :description, :story_id, :episode_img)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= simple_form_for @episode, :html => { :multipart => true }, url: story_episodes_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :episode_img %>
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<div class="col-md-6 col-md-offset-3 box">
  <h1>Editing Episode</h1>

  <%= render 'form', episode: @episode %>

  <%= link_to 'Show', edit_story_episode_path(@episode) %> |
  <%= link_to 'Back', story_episodes_path(@episode) %>
</div>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= image_tag episode.episode_img.url(:episode_index) %></td>
        <td><%= episode.title %></td>
        <td><%= episode.description %></td>
        <td><%= link_to 'Show', story_episode_path(@story, episode) %></td>
        <td><%= link_to 'Edit', edit_story_episode_path(@story, episode) %></td>
        <td><%= link_to 'Destroy', story_episode_path(@story, episode), method: :delete, confirm: 'Êtes vous sur?' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_story_episode_path(@story) %>

app/views/episodes/new.html.erb
<div class="col-md-6 col-md-offset-3 box">
  <h1>Ajouter un épisode</h1>
  <%= render 'form', episode: @episode %>
  <%= link_to 'Retour', story_episodes_path %>
</div>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tire:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @episode.description %>
</p>
  <%= image_tag @episode.episode_img.url(:episode_show) %>
<%= link_to 'Modifier', edit_story_episode_path(@episode, @story) %> |
<%= link_to 'Retour', story_episodes_path %>