config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :stories
    resources :reviews
  end
  resources :stories do
    resources :episodes
  end
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews
	has_many :stories

	has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\z/

	has_attached_file :author_pub, :styles => { :author_index => "250x350>", :author_show => "325x475>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :author_pub, :content_type => /\Aimage\/.*\z/

	has_attached_file :lapin_pub, :styles => { :lapin_index => "250x350>", :lapin_show => "325x475>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :lapin_pub, :content_type => /\Aimage\/.*\z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @category_id).order("created_at
      DESC")
    end
  end

  def show
    if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(2)
    end
  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    # @categories = Category.all.map{ |c| [c.name, c.id] }
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]
    flash.notice = "Article Created!"

    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    # @categories = Category.all.map{ |c| [c.name, c.id] }
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
  end
end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title , :description, :author, :category_id, :book_img, :author_pub, :lapin_pub)
  end

  def find_book
    @book = Book.find(params[:id])
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= link_to 'New Category', new_category_path %>
	<%= f.file_field :book_img %>
	<h1>author</h1>
	<%= f.file_field :author_pub %>
	<h1>Lapin</h1>
	<%= f.file_field :lapin_pub %>
	<%= f.input :title, label: "Titre" %>
	<%= f.input :description, label: "Description" %>
	<%= f.input :author, label: "Auteur" %>
	<%= f.submit "Soumettre" %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3 box">
  <h1>Modifier un comics</h1>
  <%= simple_form_for @book, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :book_img %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description %>
    <%= f.input :author %>
    <%= f.button :submit  %>
  <% end %>
</div>

app/views/books/index.html.erb
<% if @books.count == 0 %>
<h3 class="text-center">Il n'y a pas encore de comics dans cette catégorie.</h3>
<% else %>
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Catégorie <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
    <li class="<%= 'active' if params[:category] == category.name %>">
      <%= link_to category.name, books_path(category: category.name), class: "link" %>
    </li>
    <% end %>
  </ul>
</div>
<h2 class="text-center">Les derniers strips</h2>
<%= link_to "Sign Up", new_user_registration_path %>
<% if user_signed_in? %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Log In", new_user_session_path %>
<% end %>
<% if user_signed_in? %>
<%= link_to "Add Book", new_book_path %>
<% end %>
<h3 class="current-category text-center"><%= params[:category] %></h3>
<% @books.each do |book| %>
<div class="col-xs-18 col-sm-6 col-md-3">
  <div class="card">
    <div class="img-holder">
      <div class="overlay"><i class="fa fa-search"></i></div>
      <!-- <a href="/books/<%= book.id %>"> -->
      <a href="/books/<%= book.id %>/stories">
      <%= image_tag book.book_img.url(:book_index) %>
    </a>
  </div>
  <div class="content-holder">
    <p class="category"><%= @book = book.title %></p>
    <div class="separator">
      <span class="separator-sub"></span>
    </div>
      <!-- bootstrap WARNING LABEL FOR CATEGORY -->
    <h1>Le dernier épisode:</h1>
    <!-- <%= @story = Story.order(created_at: :desc) %> -->
    <h1>De l'histoire:</h1>
    <!-- <%= @story = Story.where(book: params[:book_id]).order(updated_at: :desc) %> -->
    <h1>Mis a jour le:</h1>
    <!-- <%= @story = Story.order("updated_at") %> -->
    <h2>Lorem ipsum dolor issi mamet consegur vat um porium</h2>
    <p class="author"><span>by</span> Phiip</p>
  </div>
</div>
</div>
<% end %>
<% end %>

<!-- <div class="row indexportal">
<div class="col-xs-6 col-sm-4">
<li><h5><a href="#">Lapin.org</a></h5></li>
<br>
<li><a href="#">Tout sur les webcomics</a></li>
<li><a href="#">24H de la BD</a></li>
<li><a href="#">Bonus</a></li>
<li><a href="#">La communauté</a></li>
<li><a href="#">Le Zine lapin</a></li>
<li><a href="#">Ressources pour les webcomics</a></li>
</div>
<div class="col-xs-6 col-sm-4 portalmiddle">
<li><h5><a href="#">Les éditions lapin</a></h5></li>
<br>
<li><a href="#">Les publications lapin</a></li>
<li><a href="#">Actualité des éditions lapin</a></li>
<li><a href="#">Les festivals</a></li>
<li><a href="#">Pour les libraires</a></li>
<li><a href="#">L’Edition en général</a></li>
<li><a href="#">Presse et médias</a></li>

</div>
<div class="col-xs-6 col-sm-4">
<li><h5><a href="#">Lapin sur les réseaux sociaux</a></h5></li>
<br>
<ul>
<li><i class="fa fa-facebook" aria-hidden="true"> <a href="https://www.facebook.com/editions.lapin" target="_blank">Les éditions sur facebook</a></i></li>
<li><i class="fa fa-pinterest" aria-hidden="true"> <a href="https://www.pinterest.com/editionslapin/" target="_blank">Les éditions sur Pinterest</a></i></li>
<li><i class="fa fa-facebook" aria-hidden="true"> <a href="https://www.facebook.com/lapin.org" target="_blank">Lapin.org sur Facebook</a></i></li>
<li><i class="fa fa-twitter" aria-hidden="true"> <a href="https://twitter.com/Lapinorg" target="_blank">Lapin.org sur Twitter</a></i></li>
<li><i class="fa fa-envelope-open" aria-hidden="true"> <a href="mailto:contact@lapin.org?subject=Phiip,%20je%20vous%20aime" target="_blank">Contact global par mail</a></i></li>
<li><i class="fa fa-twitter" aria-hidden="true"> <a href="https://twitter.com/Phiip" target="_blank">Phiip sur Twitter</a></i></li>
<li><i class="fa fa-pinterest" aria-hidden="true">  <a href="https://www.pinterest.com/phiip/" target="_blank">Phiip sur Pinterest</a></i></li>
</div>
<li class="text-center"><a href="#">Plan du site</a></li>
</ul>
</div> -->

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3 box">
  <h1>Ajouter un comics</h1>
  <%= render 'form' %>
</div>

app/views/books/show.html.erb
<!-- PAGINATION -->
<!-- <ol class="breadcrumb">
<li><%= link_to "Accueil", books_path(@book) %></li>
<li><a href="#"><%= @book.title %></a></li>
</ol> -->
<div class="container">
  <div class="row box">
    <div class="col-md-3 text-center">
      <div class="img-thumbnail"><%= image_tag @book.book_img.url(:book_show), class: "book-show" %></div>
      <h5>Moyenne des notes:</h5>
      <div class="average-review-rating" data-score="<%= @average_review %>"></div>
      <small>Basé sur <%= @book.reviews.count %> avis</small>
      <h5>Nb d'histoires:</h5>
      <h5>Nb d'épisodes:</h5>
    </div>
    <div class="col-md-9">
      <h3><%= @book.title %></h3>
      <h5><%= @book.description %></h5>
      <small>Crée le: <%= @book.created_at.strftime("%d %b %Y") %>
        <br>
        Par: <%= @book.author %></small>
      </div>
    </div>
  </div>
  <h2 class="text-center">Ep title</h2>
  <!-- EPISODES IMG NAV  -->
  <nav aria-label="...">
    <ul class="pager">
      <li><a href="#"><i class="fa fa-chevron-left" aria-hidden="true"></i></span> Previous</a></li>
      <li><a href="#">Next <i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
    </ul>
  </nav>

  <% if user_signed_in? %>
  <% if @book.user_id == current_user.id %>
  <%= link_to "Edit", edit_book_path(@book) %>
  <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Are you sure?"}  %>
  <% end %>
  <% end %>

  <%= link_to "Retour", root_path %>
  <li><%= link_to "Ajouter une histoire", new_book_story_path(@book) %></li>
  <%= link_to "Toutes les histoires", book_stories_path(@book) %>
  <li><%= link_to "Ajouter un épisode", new_story_episode_path(@book) %></li>
  <%= link_to "Tous les épisodes", story_episodes_path(@book) %>

  <!-- COMMENTS SECTION -->
  <div class="text-center">
    <h3 class="jumbotron">Commentaires</h3>

    <!-- <ul id="messages"> -->
  <!-- 1 -->
  <!-- <li>
    <div class="infos">
      <img src="http://farm5.staticflickr.com/4136/4817542998_55a7eb8d8b_q.jpg" alt="" title="by tresMunkeys" />
      <a href="http://twitter.com/webodream" class="sprite twitter">@webodream</a>
      <a href="http://www.facebook.com/groups/115089745169149" class="sprite facebook">depot.webdesigner</a>
      <a href="http://github.com/arbaoui-mehdi" class="sprite github">@arbaoui-mehdi</a>
    </div>
    <div class="content">
      <h3>
        Arbaoui Mehdi
        <b>ceo &amp; founder "depot webdesigner"</b>
      </h3>
      <p>
        Etiam iaculis, ipsum sit amet scelerisque dictum, diam justo suscipit mauris, a lacinia odio nulla et tellus. Praesent placerat ipsum sed purus rutrum vel dapibus magna scelerisque. Nulla sit amet orci at metus euismod tincidunt. Etiam <a href="#">http://www.depotwebdesigner.com</a> et nunc eu massa fermentum feugiat.
      </p>
    </div>
  </li> -->
  <!-- 2 -->
  <!-- <li>
    <div class="infos">
      <img src="http://farm3.staticflickr.com/2721/4531285963_cd28f61b16_q.jpg" alt=""  title="by tresMunkeys" />
      <a href="http://twitter.com/webodream" class="sprite twitter">@webodream</a>
      <a href="http://www.facebook.com/groups/115089745169149" class="sprite facebook">depot.webdesigner</a>
      <a href="http://github.com/arbaoui-mehdi" class="sprite github">@arbaoui-mehdi</a>
    </div>
    <div class="content">
      <h3>
        Edmundo I. Jacobi
        <b>webdeveloper</b>
      </h3>
      <p>
        Lorem ipsum non minim Excepteur Duis sunt labore ut laborum sit ullamco sed ex.Lorem ipsum dolor adipisicing ullamco cillumLorem ipsum non minim Excepteur Duis sunt labore ut laborum sit ullamco sed ex.Lorem ipsum dolor adipisicing ullamco cillumLorem ipsum non minim Excepteur Duis sunt labore ut laborum sit ullamco sed ex.Lorem ipsum dolor adipisicing ullamco cillumLorem ipsum non minim Excepteur Duis sunt labore ut laborum sit ullamco sed ex.Lorem ipsum dolor adipisicing.
      </p>
    </div>
  </li> -->

  <!-- 3 -->
  <!-- <li>
    <div class="infos">
      <img src="http://farm3.staticflickr.com/2617/3873098259_61c446da22_q.jpg" alt="" title="by tresMunkeys" />
      <a href="http://twitter.com/webodream" class="sprite twitter">@webodream</a>
      <a href="http://www.facebook.com/groups/115089745169149" class="sprite facebook">depot.webdesigner</a>
      <a href="http://github.com/arbaoui-mehdi" class="sprite github">@arbaoui-mehdi</a>
    </div>
    <div class="content">
      <h3>
        Lisa J. Escoto
        <b>webdesigner </b>
      </h3>
      <p>
        Lorem ipsum non minim Excepteur Duis sunt labore ut laborum sit ullamco sed ex.Lorem ipsum dolor adipisicing ullamco cillum in occaecat adipisicing ullamco cillum in occaecat proident commodo in <a href="http://www.google.com">http://www.google.com</a>.
      </p>
    </div>
  </li> -->

  <!-- 4 -->
  <!-- <li>
    <div class="infos">
      <img src="http://farm4.staticflickr.com/3412/3446830982_c8b55cc7e8_q.jpg" alt="" title="by tresMunkeys" />
      <a href="http://twitter.com/webodream" class="sprite twitter">@webodream</a>
      <a href="http://www.facebook.com/groups/115089745169149" class="sprite facebook">depot.webdesigner</a>
      <a href="http://github.com/arbaoui-mehdi" class="sprite github">@arbaoui-mehdi</a>
    </div>
    <div class="content">
      <h3>
        June Schreiber
        <b>CEO &amp; Founder</b>
      </h3>
      <p>
        Phasellus pharetra, libero sed egestas condimentum, ligula nibh cursus turpis, sed convallis odio lorem sit amet ligula. Suspendisse dapibus nibh nec augue placerat eleifend sit amet nec purus. Donec consectetur cursus quam eu bibendum. Nam est nisi, tincidunt mattis luctus sit amet, faucibus luctus odio. Nam placerat mauris libero. Integer fringilla nisl vitae velit lacinia eget sagittis diam feugiat. Ut et scelerisque dolor. Phasellus luctus tellus nec augue laoreet non suscipit orci condimentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eros felis, eleifend ut fringilla sit amet, vestibulum eu ligula. In venenatis aliquet tristique. Fusce tempor tincidunt adipiscing. In fermentum tincidunt purus eu tristique. Integer semper, eros et accumsan porta, purus arcu vehicula massa, quis facilisis nibh nisi non mi.
      </p>
    </div>
  </li> -->

  <!-- 5 -->
  <!-- <li>
    <div class="infos">
      <img src="http://farm4.staticflickr.com/3588/3663734351_f9cb5a6a56_q.jpg" alt="" title="by tresMunkeys" />
      <a href="http://twitter.com/webodream" class="sprite twitter">@webodream</a>
      <a href="http://www.facebook.com/groups/115089745169149" class="sprite facebook">depot.webdesigner</a>
      <a href="http://github.com/arbaoui-mehdi" class="sprite github">@arbaoui-mehdi</a>
    </div>
    <div class="content">
      <h3>
        Benita M. Futral
        <b>CEO &amp; Founder</b>
      </h3>
      <p>
        Lorem ipsum non minim Excepteur Duis sunt labore ut laborum sit ullamco sed ex.Lorem ipsum dolor adipisicing ullamco cillum
      </p>
    </div>
  </li> -->

</ul>
   <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Ajouter un commentaire</button>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="exampleModalLabel">Ajouter un commentaire</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for([@book, @book.reviews.build]) do |f| %>
            <div id="rating-form">
              <label>Rating: </label>
            </div>
            <%= f.input :comment, label: "Commentaire:" %>

            <!-- SCRIPT FOR RATING STARS -->
             <script>
            $('#rating-form').raty({
              path: '/assets/',
              scoreName: 'review[rating]'
            });
            </script>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.button :submit, :class => "btn-custom2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render @book.reviews %>
  </div>

  <!-- <div class="showportal jumbotron">
    <h3 class="text-center">Le portail Lapin</h3>
    <p>
      Le portail lapin publie gratuitement des bandes dessinées, des comics strips et
      des webcomics depuis 2001. <a href="#">Les bandes dessinées lapin</a> créées par <a href="#">les auteurs les
        plus talentueux de la webcomicosphère</a> sont en général humoristiques et/ou
        absurdes, allant de la poésie (<a href="#">la Dissonance des corps</a>, <a href="#">la plage</a>) à un humour
        très noir (<a href="#">Red Meat</a>) en passant carrément par les mathématiques (<a href="#">xkcd</a>).
        Mais lapin c'est aussi <a href="#">les éditions lapin</a>, la version papier de Lapin.org qui
        édite beaucoup de webcomics, mais aussi des <a href="#"></a>petites BD de poche, des <a href="#"></a>Ultimex,
        des <a href="#">idioties</a>, des <a href="#">lapins de bureau</a>, de beaux ouvrages (<a href="#">oooooh</a>) et des <a href="#">livres
          pour enfants</a>. Entre autres.
        </p>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <ul>
              <li><h4>Les webcomics lapin</h5></li>
                <li><a href="#">Les derniers webcomics</a></li>
                <li><a href="#">Tous les webcomics</a></li>
                <li><a href="#">Webcomics originaux FR</a></li>
                <li><a href="#">Webcomics traduits de l'anglais</a></li>
                <li><a href="#">Webcomics originaux EN</a></li>
                <li><a href="#">Notre patrimoine</a></li>
              </div>
              <div class="col-xs-6 col-sm-3">
                <li><h4>La librairie lapin</h4></li>
                <li><a href="#">Collection poches</a></li>
                <li><a href="#">Collection petit lapin</a></li>
                <li><a href="#">Collection webcomics</a></li>
                <li><a href="#">Souscription lapin</a></li>
                <li><a href="#">Tee-shirts lapin</a></li>
                <li><a href="#">Pack spéciaux pas chers</a></li>
              </div>
              <div class="col-xs-6 col-sm-3">
                <li><h4>Lapin org</h4></li>
                <li><a href="#">Les 24H de la BD</a></li>
                <li><a href="#">Parlons des webcomics</a></li>
                <li><a href="#">Bonus</a></li>
                <li><a href="#">Plan du site</a>
                  <li><a href="#">Les ressources pour les webcomics</a></li>
                  <li><a href="#">Mentions légales</a></li>
                  <li><a href="#">Contact</a></li>
                </div>
                <div class="col-xs-6 col-sm-3">
                  <li><h4>Les éditions lapin</h4>
                    <li><a href="#">Les publications lapin</a></li>
                    <li><a href="#">Actualité des éditions lapin</a></li>
                    <li><a href="#">Les festivals</a></li>
                    <li><a href="#">Espace libraires</a></li>
                    <li><a href="#">Les auteurs lapin</a></li>
                    <li><a href="#">Lapin dans la presse</a></li>
                  </ul>
                </div>
              </div>
            </div>  -->

            <!-- SCRIPT FOR RATING STARS -->
            <!-- <script>
            $('.review-rating').raty({
              readOnly: true,
              score: function() {
                return $(this).attr('data-score');
              },
              path: '/assets/'
            });
            </script>


            <script>
            $('.average-review-rating').raty({
              readOnly: true,
              path: '/assets/',
              score: function() {
                return $(this).attr('data-score')
              }
            });
            </script> -->