config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :stories
    resources :reviews
  end
  resources :stories do
    resources :episodes
  end
  root 'books#index'
end

app/models/story.rb
class Story < ApplicationRecord
 belongs_to :book
 has_many :episodes

 has_attached_file :desc_img, :styles => { :desc_index => "250x350>", :desc_show => "325x475>" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :desc_img, :content_type => /\Aimage\/.*\z/
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :set_book, expect: [:destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
    @stories = Story.where(book: params[:book_id])
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
   @story = Story.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.book = @book

    respond_to do |format|
      if @story.save!
        format.html { redirect_to @story, notice: 'L\'histoire a bien été crée.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'L\'histoire a bien été mise a jour.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy!
    respond_to do |format|
      format.html { redirect_to stories_index_url, notice: 'L\'histoire a bien été suprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
       @story = Story.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :description, :episode_img, :book_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= simple_form_for([@book, @story]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.file_field :desc_img %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<div class="col-md-6 col-md-offset-3 box">
  <h1>Editing Story</h1>
  <%= render 'form', story: @story %>
  <%= link_to 'Detail', @story %> |
  <%= link_to 'Retour', book_stories_path %>
</div>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <nav class="tab-nav" role='navigation'>
        <ul>
          <li><a class="tab1 open" href="#content-tab1">Infos</a></li>
          <li><a class="tab2" href="#content-tab2">Description</a></li>
          <li><a class="tab3" href="#content-tab3">Autheur</a></li>
          <li><a class="tab4" href="#content-tab4">...</a></li>
        </ul>
      </nav>
      <div id="content-tabs">
        <div class="content-tab open" id="content-tab1">
          <div class="container">
            <div class="row ">
              <div class="col-md-3 text-center">
                <div class="img-thumbnail"><%= image_tag @book.book_img.url(:book_show), class: "book-show" %></div>
                <h5>Moyenne des notes:</h5>
                <div class="average-review-rating" data-score=<%= @average_review %>></div>
                <small>Basé sur <%= @book.reviews.count %> avis</small>
                <h5>Nb d'histoires:</h5>
                <h5>Nb d'épisodes:</h5>
              </div>
              <div class="col-md-9">
                <h3><%= @book.title %></h3>
                <h5><%= @book.description %></h5>
                <small>Crée le: <%= @book.created_at.strftime("%d %b %Y") %>
                  <br>
                  Par: <%= @book.author %></small>
                </div>
              </div>
            </div>
          </div>
          <div class="content-tab" id="content-tab3">
            <div class="container">
              <div class="row ">
                <div class="col-md-3 text-center">
                  <div class="img-thumbnail"><%= image_tag @book.book_img.url(:book_show), class: "book-show" %></div>
                </div>
                <div class="col-md-9">
                  <h3><%= @book.title %></h3>
                    <%= image_tag @book.author_pub.url(:book_show), class: "book-show" %>
                    <br>
                    <small>Par: <%= @book.author %></small>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>
<script>
/*
* TABS SWITCHER
*/
// Refs
var tabs = $('.tab-nav').find('a'),
tabContents = $('#content-tabs').children('.content-tab');

// Switch Tab Handler
tabs.on('click', function(e) {
  e.preventDefault();
  var contentTab = $(this).attr('href');
  //tabs btn
  tabs.removeClass('open');
  $(this).addClass('open');
  //tabs content
  tabContents.removeClass('open');
  $(contentTab).addClass('open');
});


/*
* ACCORDION jQUERY UI
*/

// Init
$('.accordion').accordion({
  collapsible: false,
  active: false,
  heightStyle: "content",
  icons: { "header": "fa fa-chevron-down", "activeHeader": "fa fa-chevron-up" }
});
</script>


<h1 class="text-center">Histoires et épisodes</h1>

<%= link_to 'Nouvelle histoire', new_book_story_path(@book) %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Titre</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @stories.each do |story| %>
    <tr>
      <td><%= image_tag story.desc_img.url(:desc_show) %></td>
      <td><%= story.title %></td>
      <td><%= story.description %></td>
      <td><%= link_to 'Detail', book_story_path(@book, story) %></td>
      <td><%= link_to 'Ajouter un épisode', new_story_episode_path(story) %></td>
      <td><%= link_to 'Modifier', edit_book_story_path(@book, story) %></td>
      <td><%= link_to 'Supprimer', story, method: :delete, data: { confirm: 'Êtes vous sur ?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stories/new.html.erb
<div class="col-md-6 col-md-offset-3 box">
  <h1>Nouvelle histoire dans <%= @book.title %></h1>
  <%= render 'form', story: @story %>
  <%= link_to 'Retour', book_stories_path(@book) %>
</div>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>
<!-- EPISODES IMG -->
<%= image_tag @book.lapin_pub.url(:lapin_show) %>
<%= image_tag @book.lapin_pub.url(:author_show) %>

<%= link_to 'Modifier', edit_story_path(@story) %> |
<%= link_to 'Retour', book_stories_path(@book) %>
<br>
<%= link_to "Ajouter un épisode", new_story_episode_path(@book) %>